### ISSUE TITLE
ambiguous method definitions

### ISSUE THREAD

**Issue by stevengj** [Keno/Terminals.jl#3]
I get a bunch of warnings of the form

```
Warning: New definition 
    write(Terminal,Uint8,Any) at /Users/stevenj/.julia/Terminals/src/Terminals.jl:351
is ambiguous with 
    write(IO,Integer,Type{ReverseByteOrder}) at io.jl:46.
```

**Comment by Keno** [comment]
ah, yes, somebody merged the ByteOrder stuff, didn't they. Will see what I can do, probably just needs an annotation in Terminals.

**Comment by Keno** [comment]
Byte order changes were reverted upstream.
